dependencies:
    - python=3.7
    - ipywidgets==7.5.1
    - jupyterlab==2.1.0
    - jupyterhub-singleuser==1.1.0
    - nbconvert==5.6.1
    - notebook==6.0.3
    - nteract_on_jupyter==2.1.3
    - pandas==1.0.3
    - numpy==1.81.1
    - matplotlib==3.1.3
    - seaborn==0.10.0
    - sklearn==0.22.1
    - dtale==1.8.6
